# Generated by Django 4.1.5 on 2024-01-11 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_about'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['id'], 'verbose_name': 'About', 'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
